2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_setup.py:_flush():67] Configure stats pid to 67060
2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_setup.py:_flush():67] Loading settings from /Users/vinicius/.config/wandb/settings
2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_setup.py:_flush():67] Loading settings from /Users/vinicius/code/estudo/teste/wandb/settings
2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/vinicius/code/estudo/teste/wandb/run-20250222_011040-88s7wrat/logs/debug.log
2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/vinicius/code/estudo/teste/wandb/run-20250222_011040-88s7wrat/logs/debug-internal.log
2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_init.py:init():761] calling init triggers
2025-02-22 01:10:40,545 INFO    MainThread:67060 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-22 01:10:40,546 INFO    MainThread:67060 [wandb_init.py:init():784] starting backend
2025-02-22 01:10:40,546 INFO    MainThread:67060 [wandb_init.py:init():788] sending inform_init request
2025-02-22 01:10:40,591 INFO    MainThread:67060 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-02-22 01:10:40,591 INFO    MainThread:67060 [wandb_init.py:init():803] backend started and connected
2025-02-22 01:10:40,594 INFO    MainThread:67060 [wandb_init.py:init():896] updated telemetry
2025-02-22 01:10:40,607 INFO    MainThread:67060 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-22 01:10:41,523 INFO    MainThread:67060 [wandb_init.py:init():995] starting run threads in backend
2025-02-22 01:10:41,759 INFO    MainThread:67060 [wandb_run.py:_console_start():2377] atexit reg
2025-02-22 01:10:41,759 INFO    MainThread:67060 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-22 01:10:41,759 INFO    MainThread:67060 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-22 01:10:41,759 INFO    MainThread:67060 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-22 01:10:41,762 INFO    MainThread:67060 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-22 01:10:41,772 WARNING MsgRouterThr:67060 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/Users/vinicius/code/estudo/teste/.venvTeste/lib/python3.13/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/Users/vinicius/code/estudo/teste/.venvTeste/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/Users/vinicius/code/estudo/teste/.venvTeste/lib/python3.13/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vinicius/code/estudo/teste/.venvTeste/lib/python3.13/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/Users/vinicius/code/estudo/teste/.venvTeste/lib/python3.13/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-22 01:10:41,777 INFO    MsgRouterThr:67060 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
